### ISSUE TITLE
please update to work with gnome-shell 3.2.2

### ISSUE THREAD

**Issue by kparal** [anze3db/gnome-shell-extension-workspaceNavigator#1]
"This extension is incompatible with your version of GNOME."
https://extensions.gnome.org/extension/29/workspace-navigator/

I have Gnome Shell 3.2.2.

Also read latest comment:

> Any particular reason why the compatbility isn't set to "3.2" instead of "3.2.0, 3.2.1"? It fails to work with my 3.2.2 shell.

Please fix, thanks.

**Comment by anze3db** [comment]
Hi kpral! 

Thank you for the issue report, I have updated the version number (both here and on the shell extensions page) let me know if the latest version works for you.

Cheers

**Comment by kparal** [comment]
Seems to work perfect. Thanks.
