### ISSUE TITLE
Not working on ubuntu 12.10 and gnome shell 3.6

### ISSUE THREAD

**Issue by aabril** [anze3db/gnome-shell-extension-workspaceNavigator#3]
Needs some update workaround.

**Comment by anze3db** [comment]
Thanks for the heads up. I'll update the extension for gnome shell 3.6 before 12.10 gets released!

**Comment by anze3db** [comment]
I've made an update, let me know if it works for you. The new version should pop up on https://extensions.gnome.org/extension/29/workspace-navigator/ soon. 

Cheers.
